<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <SPTDir Condition="'$(SPTDir)' == ''">S:\SPT-Dev\4.0</SPTDir>
    </PropertyGroup>
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>SkillMultiplier</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <ModAuthor>Dazzuh</ModAuthor>
        <Version>2.0.0</Version>
        <OutputPath>bin\$(Configuration)\$(ProjectName)\$(AssemblyName)\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="SPTarkov.Common">
            <HintPath>$(SPTDir)\SPT\SPTarkov.Common.dll</HintPath>
        </Reference>
        <Reference Include="SPTarkov.DI">
            <HintPath>$(SPTDir)\SPT\SPTarkov.DI.dll</HintPath>
        </Reference>
        <Reference Include="SPTarkov.Server.Core">
            <HintPath>$(SPTDir)\SPT\SPTarkov.Server.Core.dll</HintPath>
        </Reference>
        <Reference Include="SemanticVersioning">
            <HintPath>$(SPTDir)\SPT\SemanticVersioning.dll</HintPath>
        </Reference>
    </ItemGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>None</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <GenerateDependencyFile>false</GenerateDependencyFile>
        <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    </PropertyGroup>

</Project>
